#!/bin/bash

check_owncloud_downloads () {
# Read access.log for identify downloads, exclude event generated by pdfviewer, and get token from URL for variable
dwld_token=`tail -8 /var/log/nginx/access.log | grep -v "files_pdfviewer" | grep -i --line-buffered '/[a-z]/.*/download' | sed 's/\// /g' | awk '{print$10}' |uniq`
}
link_name="one_download"

while check_owncloud_downloads
do
       if [ -n "$dwld"  ]
       then     # Find token in DB, and choose our link name from others 
                VAR=$( mysql -D owncloud -e "select share_name from oc_share where token = '$dwld_token'" | grep -c $link_nmae )
                if [ $VAR = "1" ]
                then # Remove link from DB
                mysql -D owncloud -e "delete from oc_share where token = '$dwld_token'"
                fi
       else
                sleep 1
       fi
done
