#!/bin/bash

check_owncloud_downloads () {
# Read access.log for identify downloads, exclude event generated by pdfviewer, and get token from URL for variable
dwld_token=`tail -8 /var/log/nginx/access.log | grep -v "files_pdfviewer" | grep -i --line-buffered '/[a-z]/.*/download' | sed 's/\// /g' | awk '{print$10}' |uniq`
}

while check_owncloud_downloads
do
       if [ -n "$dwld"  ]
       then
           # Delete link from datadase
           mysql -D owncloud -e "delete from oc_share where token = '$dwld_token'"
       else
           sleep 1
       fi
done
